version: "2.0"
services:
  i3-build:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: EMBED-EduKit-Build
    volumes:
      - "./work:/root/work"
    command: /bin/bash
    stdin_open: true # docker run -i
    tty: true # docker run -t
